In actual world we dont have to create the dataframe manually the dataframes can be in the form of CSV or JSON

In [115]:
import pandas as pd

In [116]:
coffee= pd.read_csv("F:\Machine Learning 2026\Pandas\Github Repo Tutorial\complete-pandas-tutorial\warmup-data\coffee.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\lenovo\AppData\Local\Temp\ipykernel_11340\751680953.py:1: SyntaxWarning: invalid escape sequence '\M'
  coffee= pd.read_csv("F:\Machine Learning 2026\Pandas\Github Repo Tutorial\complete-pandas-tutorial\warmup-data\coffee.csv")

In [117]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [118]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [119]:
coffee.sample(10,random_state=1) #random_State le data same aauxa and the sample is used to view random rows 
#Try Random State 2

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

<h3> LOC vs ILOC </h3>
LOC- Label Based ==> Give me rows/cols by their name
ILOC- Position Based ==> Give me rows/cols by their position number

In [120]:
coffee.loc[[0,1,2]]
coffee.loc[0:2]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [121]:
coffee.loc[5:10,["Coffee Type","Units Sold"]]

   Coffee Type  Units Sold
5        Latte          25
6     Espresso          40
7        Latte          30
8     Espresso          45
9        Latte          35
10    Espresso          45

In [122]:
coffee.iloc[5:10,[1,2]] 
#notice Smth Different? The Last Row is exclusive in iloc

  Coffee Type  Units Sold
5       Latte          25
6    Espresso          40
7       Latte          30
8    Espresso          45
9       Latte          35

In [123]:
#you can Change the index by this command 
coffee.index=coffee.Day
coffee.index=coffee['Day']
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [124]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [125]:
coffee.loc["Monday":"Sunday",["Coffee Type","Units Sold"]]

          Coffee Type  Units Sold
Day
Monday       Espresso          25
Monday          Latte          15
Tuesday      Espresso          30
Tuesday         Latte          20
Wednesday    Espresso          35
Wednesday       Latte          25
Thursday     Espresso          40
Thursday        Latte          30
Friday       Espresso          45
Friday          Latte          35
Saturday     Espresso          45
Saturday        Latte          35
Sunday       Espresso          45
Sunday          Latte          35

In [126]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [127]:
coffee.index=[a for a in range(1,15)]

In [128]:
coffee

          Day Coffee Type  Units Sold
1      Monday    Espresso          25
2      Monday       Latte          15
3     Tuesday    Espresso          30
4     Tuesday       Latte          20
5   Wednesday    Espresso          35
6   Wednesday       Latte          25
7    Thursday    Espresso          40
8    Thursday       Latte          30
9      Friday    Espresso          45
10     Friday       Latte          35
11   Saturday    Espresso          45
12   Saturday       Latte          35
13     Sunday    Espresso          45
14     Sunday       Latte          35

Say You want to change the value from 15 to 20 you do the following

In [129]:
coffee.head()

         Day Coffee Type  Units Sold
1     Monday    Espresso          25
2     Monday       Latte          15
3    Tuesday    Espresso          30
4    Tuesday       Latte          20
5  Wednesday    Espresso          35

In [130]:
coffee.loc[2, 'Units Sold'] = 30

In [131]:
coffee.head()

         Day Coffee Type  Units Sold
1     Monday    Espresso          25
2     Monday       Latte          30
3    Tuesday    Espresso          30
4    Tuesday       Latte          20
5  Wednesday    Espresso          35

In [132]:
#if you gonna extract just one value than you could do 
print(coffee.loc[1,'Units Sold'])

25

In [133]:
#better way of doing the same thing 
print(coffee.at[1,"Units Sold"])
#if you pass multiple values that it's gonna yell at you fr

25

In [147]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=False)
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[0,0])
# 0 is equivalent to False in Python.
# False means sort in descending order.

          Day Coffee Type  Units Sold
9      Friday    Espresso          45
11   Saturday    Espresso          45
13     Sunday    Espresso          45
7    Thursday    Espresso          40
10     Friday       Latte          35
12   Saturday       Latte          35
14     Sunday       Latte          35
5   Wednesday    Espresso          35
2      Monday       Latte          30
8    Thursday       Latte          30
3     Tuesday    Espresso          30
6   Wednesday       Latte          25
1      Monday    Espresso          25
4     Tuesday       Latte          20

In [148]:
coffee.loc[coffee["Units Sold"]>20]

          Day Coffee Type  Units Sold
1      Monday    Espresso          25
2      Monday       Latte          30
3     Tuesday    Espresso          30
5   Wednesday    Espresso          35
6   Wednesday       Latte          25
7    Thursday    Espresso          40
8    Thursday       Latte          30
9      Friday    Espresso          45
10     Friday       Latte          35
11   Saturday    Espresso          45
12   Saturday       Latte          35
13     Sunday    Espresso          45
14     Sunday       Latte          35

In [149]:
#Creating Custom Data Frame using Dictionary 

added_coffee = pd.DataFrame({
    "Coffee Type": ["Latte","Espresso","Mocha"],
    "Units Sold": [50,70,30]
})

In [151]:
added_coffee

  Coffee Type  Units Sold
0       Latte          50
1    Espresso          70
2       Mocha          30